### ISSUE TITLE
AS2 component has no configuration options

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#286]
### Describe the Bug

When adding the AS2 component from the Kaoto catalog to the canvas I have no configuration options. Test both as `from` and as `to` endpoint.

### Steps to Reproduce the Bug or Issue

Add an AS2 component endpoint to the canvas and click it to open the config panel.

### Screenshots or Videos

![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/b12b2c9f-c02d-4216-ae32-c33d1687760f)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by tplevko** [comment]
Looked at how this property was handled in the kaoto-ui. There seems to be a recommendation "Please use the source code editor to configure this property."

I think this issue is causing more components not be configurable ATM, e.g. the google sheets and calendar

![Screenshot from 2023-11-24 12-50-00](https://github.com/KaotoIO/kaoto-next/assets/4180208/b20ff475-9fdb-4c5f-bb25-2503b6181841)

**Comment by lhein** [comment]
duplicates #448
