### ISSUE TITLE
`expression` property is unexpectedly added to the other step

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#385]
### Describe the Bug

Race condition?

### Steps to Reproduce the Bug or Issue

1. Click setHeader step
2. Input simple expression
3. Click log step
4. Click setHeader step
5. Change the language to constant
6. Input constant expression
7. Click log step
8. Click setHeader step

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/265462/016f203d-f42b-4bc9-b60f-de1473e3b1c2

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by igarashitm** [comment]
`ExpressionEditor.handleOnChange` is invoked only on `setHeader` node. It would be written at some different place...

**Comment by igarashitm** [comment]
#416 could be coming from a same root cause with this one. If I close the step configuration form every time before opening another one, this doesn't happen.

**Comment by igarashitm** [comment]
So when I click `setHeader` step and then `log` step, the form for the `log` step is rendered with `setHeader` model, then re-rendered with weirdly updated model

my print debug 
```
>>>> Rendering Form for log-3832 {"id":"setHeader-7669","expression":{"constant":{"expression":"a"}}}
CanvasForm.tsx:60 
>>>> Rendering Form for log-3832 {"id":"log-1675","message":"template message2","expression":{"simple":{}}}
```

If I understand correctly, the model object is retrieved after the initial rendering through `useEffect()` here
https://github.com/KaotoIO/kaoto-next/blob/main/packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx#L38
Then it triggers re-render?

@lordrip is my assumption legit? do you have an idea to solve this in React in general?

**Comment by lordrip** [comment]
@igarashitm I think there's part of the truth on that. After debugging it, the property in the wrong node is [added here](https://github.com/KaotoIO/kaoto-next/blob/32e0a5873a7fcf8c72b3c08f46de8a927cad4e45/packages/ui/src/components/Visualization/Canvas/expression.service.ts#L84-L88).

This is what we're doing at the moment:

1. Set `model=undefined` in line #69 
2. If the `parentModel.expression` property is defined (node definition) we parse it, otherwise, we try to check what the expression might be. Since we don't have such a property, we exhaust the `for` statement in line # 77 .
3. In line # 84, if we haven't figured out which expression it was, we set the `parentModel.expression` property in line # 85

The latter is what is ultimately causing the property to be added to the component.

Now, the first question remains, why the `isExpressionAwareStep` property is not updated and attempts to show the `ExpressionEditor` component?

**Comment by lordrip** [comment]
Alright, this is what's happening:

1. Click on `setHeader`
2. Since [we have defaults coming from the `useState`](https://github.com/KaotoIO/kaoto-next/blob/32e0a5873a7fcf8c72b3c08f46de8a927cad4e45/packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx#L23-L25), the `useEffect` is skipped.
3. [`isExpressionAwareStep` is calculated](https://github.com/KaotoIO/kaoto-next/blob/32e0a5873a7fcf8c72b3c08f46de8a927cad4e45/packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx#L51C9-L53), and returns `true`, since `setHeader` contains an `expression` property.
4. The `ExpressionEditor` component is shown.

Now, when clicking on `log`, here's what happens:
1. The `props.selectedNode` property change
2. The `ExpressionEditor` component is still shown as the `isExpressionAwareStep` property is not recalculated yet but the `selectedNode` is the `log`
3. **The `ExpressionEditor` adds the property to the wrong node**
4. The pending `useEffect` gets executed causing another rerender, in this case also forcing to recalculate the `useMemo` `isExpressionAwareStep` property, hence hiding the `ExpressionEditor`

**Comment by lordrip** [comment]
Your PR (https://github.com/KaotoIO/kaoto-next/pull/461/files) fixes it because `useMemo` gets recalculated as soon as the property changes.
