### ISSUE TITLE
name attribute is lost sometimes for setHeader

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#518]
1. Create a new route
2. add a setHeader
3. configure expression language JQ
4. set the expression to .id
5. set the result type to "java.lang.String"
6. set the name field to "id"
7. enable "trim" checkbox
8. add another setHeader
10. configure expression language JQ
11. set the expression to .name
12. set the result type to "java.lang.String"
13. set the name field to "name"
14. enable "trim" checkbox
15. select the former setHeader to open the config panel
16. see that the name field is now blank
17. select the later setHeader
18. see that the name field is now blank too

**Comment by apupier** [comment]
![setHeaderBug](https://github.com/KaotoIO/kaoto-next/assets/1105127/a03295e4-7c86-41ac-b920-1d8f127cd110)

**Comment by lordrip** [comment]
Edited the reproduction steps as the problem comes from updating the expression field **AFTER** editing the endpoint parameters.

This happens because the `ExpressionField` has stale data from the node, effectively removing any configuration made before editing the expression.

Alternatively, if the expression is completely adjusted and after that, the endpoint parameters are adjusted, the issue is not present.

**Comment by lhein** [comment]
Good find.
