### ISSUE TITLE
Close catalog detail modal by clicking outside the detail

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#546]
### Please describe the feature that you want to propose

Currently the users have to click the cross sign in case they want to close the catalog detail modal. It would improve the usability, if it could be closed by clicking outside the displayed modal.

 

https://github.com/KaotoIO/kaoto-next/assets/4180208/7caf9f69-ddc6-4003-8394-90e119a7b135

**Comment by lordrip** [comment]
Hi @tplevko, since the `Modal` component doesn't have an `onOutsideClick` property or similar, I checked it with the Patternfly team and they mentioned that the current implementation is the recommended approach, since having a close or a cancel button it's more explicit.

If we want to implement it ourselves, I fear that we're gonna need to implement our own custom `Modal`, leveraging the `Backdrop` component with something else. Curious enough, the `Backdrop` component doesn't have a `onClick` property either 😅 .

I'll leave it to you to close the issue or maybe you have another idea.

**Comment by tplevko** [comment]
Thanks @lordrip for the feedback. In case the way the patternfly team recommends the usage of an explicit element for closing the modal, we should probably follow their guidelines, to adhere to the look and feel of our other products.

Closing this issue, we can revisit in case they decide to add this functionality to patternfly.
