### ISSUE TITLE
OnException route name not corresponding to the set name in side panel

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#866]
### Describe the Bug

The onException type route name in side panel is not corresponding to the route name set. 

### Steps to Reproduce the Bug or Issue

1. create route: 
```
- onException:
    id: onException-1234
```
2. see the design page
3. see the side panel - the name on the top is not the same

### Screenshots or Videos

![Screenshot from 2024-02-22 15-39-32](https://github.com/KaotoIO/kaoto-next/assets/4180208/d12958fa-e087-4e0d-babe-0f8d9a7a36e1)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
Yes, that's "expected" in terms of the title that we see at the top (`onException-3913`) it's the internal node id, whereas the description one is the node id as seen in the route.

The fix should be geared towards moving the `onException` title to the top, and remove the ID, since is in the form anyways
